# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tE7O3chs4agfiyXjtBBo2SBAtP7pC7vN
"""

import pandas as pd
import numpy as nm  
import matplotlib.pyplot as mtp

from google.colab import files
import io
updated=files.upload()

data=pd.read_csv("Social_Network_Ads.csv")
data.tail()

m=data.iloc[:,[2,3]].values
n=data.iloc[:,4].values

from sklearn.model_selection import train_test_split
m_train,m_test,n_train,n_test=train_test_split(m,n,test_size=0.20,random_state=0)

n

from sklearn.preprocessing import StandardScaler
st_x=StandardScaler()
m_train=st_x.fit_transform(m_train)
m_test=st_x.transform(m_test)

from sklearn.linear_model import LogisticRegression  
classifier= LogisticRegression(random_state=0)  
classifier.fit(m_train, n_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,  
                   intercept_scaling=1, l1_ratio=None, max_iter=100,  
                   multi_class='warn', n_jobs=None, penalty='l2',  
                   random_state=0, solver='warn', tol=0.0001, verbose=0,  
                   warm_start=False)

n_pred= classifier.predict(m_test)

from sklearn.metrics import confusion_matrix 
cm= confusion_matrix()

from matplotlib.colors import ListedColormap  
x_set, y_set = m_train, n_train  
x1, x2 = nm.meshgrid(nm.arange(start = x_set[:, 0].min() - 1, stop = x_set[:, 0].max() + 1, step  =0.01),  
nm.arange(start = x_set[:, 1].min() - 1, stop = x_set[:, 1].max() + 1, step = 0.01))  
mtp.contourf(x1, x2, classifier.predict(nm.array([x1.ravel(), x2.ravel()]).T).reshape(x1.shape),  
alpha = 0.75, cmap = ListedColormap(('purple','green' )))  
mtp.xlim(x1.min(), x1.max())  
mtp.ylim(x2.min(), x2.max())  
for i, j in enumerate(nm.unique(y_set)):  
    mtp.scatter(x_set[y_set == j, 0], x_set[y_set == j, 1],  
        c = ListedColormap(('purple', 'green'))(i), label = j)  
mtp.title('Logistic Regression (Training set)')  
mtp.xlabel('Age')  
mtp.ylabel('Estimated Salary')  
mtp.legend()  
mtp.show()